apiVersion: apps/v1
kind: Deployment

metadata:
  name: coffer-frontend

spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: API_BASE_URL
              value: "https://coffer.136.69.31.235.nip.io"