apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - ingress.yaml
  - managed-certificate.yaml

images:
  - name: asia-south1-docker.pkg.dev/coffer-506809/coffer-docker/backend
    newTag: prod

  - name: asia-south1-docker.pkg.dev/coffer-506809/coffer-docker/frontend
    newTag: prod
