apiVersion: v1
kind: Service

metadata:
  name: coffer-backend
  annotations:
    cloud.google.com/backend-config: '{"default": "coffer-backend-config"}'

spec:
  selector:
    app: coffer-backend

  ports:
    - port: 3000
      targetPort: 3000

  type: ClusterIP